### ISSUE TITLE
Same simple code doesn't run after v4.7.0+

### ISSUE THREAD

**Issue by ramazanpolat** [arangodb/arangodb-java-driver#264]
I have a simple code which inserts a document. 

```
final ArangoDB arangoDB = new ArangoDB.Builder().host(ARANGO_HOST, ARANGO_PORT)
                .user(ARANGO_USER).password(ARANGO_PASSWORD).build();
        String dbName = "cache";
        String collectionName = "cache1";

        BaseDocument myObject = new BaseDocument();
        myObject.addAttribute("a", "Foo");
        myObject.addAttribute("b", 42);
        try {
            arangoDB.db(dbName).collection(collectionName).insertDocument(myObject);
            System.out.println("Document created");
        } catch (ArangoDBException e) {
            System.err.println("Failed to create document. " + e.getMessage());
        } finally {
            arangoDB.shutdown();
        }
```

This code is borrowed from [official arangodb tutorials](https://www.arangodb.com/tutorials/tutorial-sync-java-driver/) and it works in driver v4.2.2 -> v4.6.1. 

`Document created`

But all recent drivers starting from v4.7.0 can't run the code. Each version dumps different error. 
For example, v4.7.3 gives the following output. Even v5+ doesn't work. Appearently something changed after v4.7.0 that is not mentioned in documents(or maybe I couldn't find it even if it's mentioned).

```
Exception in thread "main" java.lang.NoSuchMethodError: com.arangodb.velocypack.VPackDeserializationContext.deserialize(Lcom/arangodb/velocypack/VPackSlice;Ljava/lang/reflect/Type;)Ljava/lang/Object;
	at com.arangodb.internal.velocypack.VPackDeserializers$1.deserialize(VPackDeserializers.java:79)
	at com.arangodb.internal.velocypack.VPackDeserializers$1.deserialize(VPackDeserializers.java:67)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:546)
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:396)
	at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:55)
	at com.arangodb.internal.util.DefaultArangoSerialization.deserialize(DefaultArangoSerialization.java:58)
	at com.arangodb.internal.velocystream.VstCommunication.createResponse(VstCommunication.java:122)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143)
	at com.arangodb.internal.velocystream.VstCommunicationSync.authenticate(VstCommunicationSync.java:161)
	at com.arangodb.internal.velocystream.VstCommunicationSync.authenticate(VstCommunicationSync.java:47)
	at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:83)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:139)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:47)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:102)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocument(ArangoCollectionImpl.java:73)
	at com.rambo.App.arango3(App.java:86)
	at com.rambo.App.main(App.java:111)

```

* __ArangoDB Version__:        3.4.5
* __Storage Engine__: RocksDB
* __Deployment Mode__:    Single Server
* __Deployment Strategy__: docker
* __Infrastructure__:            digitalocean
* __Operating System__:    Windows 7 x64
* __Total RAM in your machine__:        4GB
* __Disks in use__:       SSD

**Comment by rashtao** [comment]
@ramazanpolat I cannot reproduce the problem. Your snippet is working correctly for me.
What I can see in your error stack is that you have a binary compatibility problem related to the dependency `com.arangodb:velocypack`. 
Are you using java version 8+?
Are you maybe importing a custom version of such dependency in your project?

**Comment by ramazanpolat** [comment]
I was using Java 1.8. It has been a long time since I opened this issue. Can't have the setup now to reproduce it.
